In [429]:
import numpy as np
import pandas as pd

In [430]:
example_file = 'example.txt'
data_input_file = 'data_input.txt'
data_input_file_2 = 'data_input_2.txt'

In [431]:
data = example_file
# data = data_input_file
# data = data_input_file_2
df = pd.read_csv(data, sep=" ", header=None)

In [432]:
# df.shape[0]

In [433]:
# print(list(df[0][0]))
# print(len(list(df[0][0])))

In [434]:
#df.head()

In [435]:
map_size_x = len(list(df[0][0]))
map_size_y = len(df)
print(map_size_x, map_size_y)

map = np.zeros((df.shape[0], len(list(df[0][0]))), dtype=int)
#print(map.shape)
#print(map)

12 12


In [436]:
# equation of a line y = mx + c
def find_line_equation(point_1, point_2):
    x1 = point_1[0]
    y1 = -1*point_1[1]
    x2 = point_2[0]
    y2 = -1*point_2[1]
    slope = (y2-y1)/(x2-x1)
    y_intercept = (y1 - slope*x1)

    return slope, y_intercept

# point_1 = [8, 1]
# point_2 = [5, 2]
point_1 = [8, 8]
point_2 = [9, 9]
m, c = find_line_equation(point_1, point_2)
print("Line Solution is y = {m}x + {c}".format(m=m,c=c))

x = point_2[0]
y = m*x + c
print(y)


Line Solution is y = -1.0x + 0.0
-9.0


In [437]:
distance_x = (point_2[0] - point_1[0])
print(distance_x)
x = point_1[0] - distance_x
y = m*x + c
print(x, y)
x = point_2[0] + distance_x
y = m*x + c
print(x, y)

1
7 -7.0
10 -10.0


In [438]:
# find_antinodes is a function creates a virtual line and ...
def find_antinodes_from_two_map_points(point_1, point_2):
    m, c = find_line_equation(point_1, point_2)
    distance_x = (point_2[0] - point_1[0])
    #print(distance_x)
    x = point_1[0] - distance_x
    y = int(m*x + c)
    #print(x, y)
    antinode_1 = [x, -y]
    x = point_2[0] + distance_x
    y = int(m*x + c)
    #print(x, y)
    antinode_2 = [x, -y]
    return antinode_1, antinode_2

point_1 = [8, 1]
point_2 = [5, 2]
# point_1 = [8, 8]
# point_2 = [9, 9]
antinode_1, antinode_2 = find_antinodes_from_two_map_points(point_1, point_2)

print(antinode_1, antinode_2)

[11, 0] [2, 3]


In [439]:
def place_antinode_in_map(map, antinode_1, antinode_2):
    map_size_x = map.shape[1]
    map_size_y = map.shape[0]
    # antinode[0]: x (columns), antinode[1]: y (rows)
    if 0 <= antinode_1[0] <= map_size_x-1 and 0 <= antinode_1[1] <= map_size_y-1:
        map[antinode_1[1]][antinode_1[0]] = 1
    if 0 <= antinode_2[0] <= map_size_x-1 and 0 <= antinode_2[1] <= map_size_y-1:
        map[antinode_2[1]][antinode_2[0]] = 1

map = np.zeros((df.shape[0], len(list(df[0][0]))), dtype=int)
place_antinode_in_map(map, [0, 0], [2,2])
place_antinode_in_map(map, [-1, -1], [1,1])
place_antinode_in_map(map, [11, 0], [1,1])
#print(map)

In [440]:
map = np.zeros((df.shape[0], len(list(df[0][0]))), dtype=int)
for y1 in range(map.shape[0]):
    row_list =  list(df[0][y1])
    for x1, element in enumerate(row_list):
        if element != '.' and element.isalnum():
            for y2 in range(map.shape[0]):
                row_list_2 =  list(df[0][y2])
                for x2, element_2 in enumerate(row_list_2):
                    if x1 == x2 and y1 == y2:
                        skip = True
                    else:
                        skip = False
                    if not skip and element_2 == element:
                        antinode_1, antinode_2 = find_antinodes_from_two_map_points([x1, y1], [x2, y2])
                        row_list_3 =  list(df[0][y1])
                        place_antinode_in_map(map, antinode_1, antinode_2)
                        # print(element, element_2)
                        # print([x1, y1], [x2, y2])
                        # print(antinode_1, antinode_2)
                        #print((element, element_2), ([x1, y1], [x2, y2]), (antinode_1, antinode_2))
                        # print(map)

In [441]:
map

array([[0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0]])

In [442]:
print(map)
print(np.count_nonzero(map))

[[0 0 0 0 0 0 1 0 0 0 0 1]
 [0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 1 0]
 [0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0]
 [0 1 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 1 0]]
14
