In [1]:
import numpy as np
import pandas as pd

In [2]:
data_folder_path = r'C:\Code\Personal\adventofcode2024\05\Boulus'
rules_example_file = 'rules_example.txt'
example_file = 'example.txt'
rules_input_file = 'rules_input.txt'
input_file = 'input.txt'
# file_2 = 'data.txt'

In [3]:
data_table = pd.read_csv(rules_example_file, sep="|", header=None)
#data_table = pd.read_csv(rules_input_file, sep="|", header=None)

In [4]:
data_table.head()

0   1
0  47  53
1  97  13
2  97  61
3  97  47
4  75  29

In [5]:
df_sorted = data_table.sort_values(by=[0, 1])

In [6]:
df_sorted.head()

0   1
7   29  13
13  47  13
18  47  29
0   47  53
16  47  61

In [7]:
def does_rule_pair_exist(data_frame, number_1, number_2):
    df_1 = df_sorted.loc[df_sorted[0]==number_1]
    df_2 = df_1.loc[df_1[1]==number_2]
    return (len(df_2)>=1)


number_1 = 75
number_2 = 29
print(does_rule_pair_exist(df_sorted, number_1, number_2))

True


In [8]:
array_test = np.array([75, 47, 61, 53, 29])
array_test = np.array([75, 97, 47, 61, 53])
print(array_test[:-1])
print(len(array_test))

[75 97 47 61]
5


In [9]:
len_array_test = len(array_test[:-1])
pair_rule_validity_list = []
for i in array_test[:-1]:
    for j in array_test[1:]:
        pair_rule_validity_list.append(does_rule_pair_exist(df_sorted, i, j))
    print(pair_rule_validity_list)
    pair_rule_validity_list = []

[False, True, True, True]
[False, True, True, True]
[False, False, True, True]
[False, False, False, True]


In [10]:
def test_array_validity(array):
    valid_list = False
    len_array = len(array)
    pair_rule_validity_list = []
    for index, i in enumerate(array[:-1]):
        for j in array[1:]:
            pair_rule_validity_list.append(does_rule_pair_exist(df_sorted, i, j))
        #print(pair_rule_validity_list)
        #print(len_array-index-1, sum(pair_rule_validity_list))
        if (len_array-index-1 != sum(pair_rule_validity_list)):
            return valid_list
        pair_rule_validity_list = []
    valid_list = True
    return valid_list


In [11]:
does_rule_pair_exist(df_sorted, 97, 75)

True

In [12]:
def make_array_valid(array_input):
    array = array_input.copy()
    valid_list = False
    len_array = len(array)
    pair_rule_validity_list = []
    array_updated = False
    while not valid_list:
        array_updated = False
        print("Not valid ", array)
        pair_rule_validity_list = []
        for index, i in enumerate(array[:-1]):
            if array_updated:
                continue
            for index_j, j in enumerate(array[1:]):
                if array_updated:
                    continue
                if not does_rule_pair_exist(df_sorted, i, j):
                    array[index] = j
                    array[index_j+1] = i
                    print(array, "array updated")
                    array_updated = True
                    continue
                pair_rule_validity_list.append(does_rule_pair_exist(df_sorted, i, j))
            print(pair_rule_validity_list)
            #print(len_array-index-1, sum(pair_rule_validity_list))
            if (len_array-index-1 != sum(pair_rule_validity_list)):
                valid_list = False
                print("continue")
                continue
            pair_rule_validity_list = []
        if not array_updated:
            valid_list = True
    return valid_list

In [13]:
test_array_validity(array_test)

False

In [14]:
print(array_test)
#make_array_valid(array_test)

[75 97 47 61 53]


In [15]:
data = example_file
#data = input_file
valid_lists_middle_points = []
for i, line in enumerate(open(data)):
    line_list = np.array(line.split(','), dtype=int)
    print(line_list, test_array_validity(line_list), line_list[int((len(line_list) - 1)/2)]) 
    if test_array_validity(line_list):
        valid_lists_middle_points.append(line_list[int((len(line_list) - 1)/2)])
print(sum(valid_lists_middle_points))

[75 47 61 53 29] True 61
[97 61 53 29 13] True 53
[75 29 13] True 29
[75 97 47 61 53] False 47
[61 13 29] False 13
[97 13 75 29 47] False 75
143
